/*==============================================================*/
/* Public procedure :  proc_dropifexists(p_table in varchar2)   */
/* Description:        判断是否存在要创建的表，存在则删掉       */
/* Create on:          2018-05-28  14:58:32                     */
/*==============================================================*/
CREATE OR REPLACE PROCEDURE PROC_DROPIFEXISTS(P_TABLE IN VARCHAR2)
IS
V_COUNT NUMBER(10);
BEGIN
  SELECT COUNT(*)
  INTO V_COUNT
  FROM USER_TABLES
  WHERE TABLE_NAME = UPPER(P_TABLE);
  IF V_COUNT > 0 
  THEN
     EXECUTE IMMEDIATE 'drop table '||P_TABLE||' purge';
  END IF;
END PROC_DROPIFEXISTS;
commit;

/*==============================================================*/
/* Decription: 如果存在要创建的表则将其删除                     */
/*==============================================================*/
CALL PROC_DROPIFEXISTS('DEMO');
CREATE TABLE demo(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR2(50) NOT NULL,
    status NUMBER(2) default 1,
	create_time TIMESTAMP default systimestamp,
    update_time TIMESTAMP default systimestamp,
    PRIMARY KEY(id)
);
comment on table "DEMO" is '建表模板表';
comment on column "DEMO"."STATUS" is '状态';
comment on column "DEMO"."CREATE_TIME" is '创建时间';
comment on column "DEMO"."UPDATE_TIME" is '更新时间';

insert into demo(content) values('dsds');
insert into demo(content) values('dsds');
insert into demo(content) values('dsds');
insert into demo(content) values('dsds');

